### ISSUE TITLE
Bootstrap 4 version

### ISSUE THREAD

**Issue by zedtux** [Yago/Bootsketch#10]
Bootstrap 4 is almost here, would be great to have a bootstrap 4 version of this really nice little thing :)

**Comment by Yago** [comment]
Sure ! I'll keep it in a corner of my mind to update this repo soon 😄

**Comment by zedtux** [comment]
Bootstrap 4 is now out, will you have a look @Yago ?

**Comment by zedtux** [comment]
@Yago any update here?
