### ISSUE TITLE
Demo loads font file over HTTP

### ISSUE THREAD

**Issue by 0x62** [Yago/Bootsketch#6]
Anyone using HTTPS Everywhere or a similar plugin won't be able to use the site as the Google Fonts stylesheet is loaded over explicit http.

Consider adjusting it to use explicit https or implicit (through a protocol relative url).

**Comment by njt1982** [comment]
I've had to hack this line https://github.com/Yago/Bootsketch/blob/master/assets/sass/bootsketch.scss#L3 to force it onto HTTPS.

I can't think of any good reason why that shouldn't be the default now.

**Comment by njt1982** [comment]
I have addressed this in #9...
